/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sistema_de_musicas;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JFernandes
 */
public class AvaliarMusicasTela extends javax.swing.JFrame {

    /**
     * Creates new form AvaliarMusicasTela
     */
    public AvaliarMusicasTela() {
        super ("Avaliar músicas");        
        initComponents();
        buscarMusicas();
        buscarMinhasAvaliacoes();
        setLocationRelativeTo(null);
    }    
    
    private void buscarMusicas (){
        try{
            List <Musica> musicas = MusicaDAO.listarMusicas(Usuario.getInstance());
            escolhaAMusicaComboBox.setModel(new DefaultComboBoxModel<>(musicas.toArray(new Musica[0])));
            
        }
        catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tente novamente mais tarde");
        }
    }
    
    private void buscarMinhasAvaliacoes (){
        try{
            List <Musica> musicas = MusicaDAO.listarMinhasAvaliacoes(Usuario.getInstance());
            minhasAvaliacoesComboBox.setModel(new DefaultComboBoxModel<>(musicas.toArray(new Musica[0])));
            
        }
        catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tente novamente mais tarde");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avaliarMusicasPanel = new javax.swing.JPanel();
        avaliarMusicaButton = new javax.swing.JButton();
        avaliarNotaTextField = new javax.swing.JTextField();
        voltarButton = new javax.swing.JButton();
        escolhaAMusicaComboBox = new javax.swing.JComboBox<>();
        reavaliarMusicaButton = new javax.swing.JButton();
        minhasAvaliacoesComboBox = new javax.swing.JComboBox<>();
        reavaliarNotaTextField = new javax.swing.JTextField();
        idReavaliacaoTextField = new javax.swing.JTextField();
        idAvaliacaoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        avaliarMusicasPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Avaliar músicas"));

        avaliarMusicaButton.setText("Avaliar música");
        avaliarMusicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarMusicaButtonActionPerformed(evt);
            }
        });

        avaliarNotaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite a nota (1 a 5)"));

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        escolhaAMusicaComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha a música que você quer avaliar"));
        escolhaAMusicaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolhaAMusicaComboBoxActionPerformed(evt);
            }
        });

        reavaliarMusicaButton.setText("Reavaliar Música");
        reavaliarMusicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reavaliarMusicaButtonActionPerformed(evt);
            }
        });

        minhasAvaliacoesComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Minhas avaliações"));
        minhasAvaliacoesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minhasAvaliacoesComboBoxActionPerformed(evt);
            }
        });

        reavaliarNotaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite a nota (1 a 5)"));

        idReavaliacaoTextField.setEditable(false);

        idAvaliacaoTextField.setEditable(false);

        javax.swing.GroupLayout avaliarMusicasPanelLayout = new javax.swing.GroupLayout(avaliarMusicasPanel);
        avaliarMusicasPanel.setLayout(avaliarMusicasPanelLayout);
        avaliarMusicasPanelLayout.setHorizontalGroup(
            avaliarMusicasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avaliarMusicasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(avaliarMusicasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escolhaAMusicaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minhasAvaliacoesComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(avaliarMusicasPanelLayout.createSequentialGroup()
                        .addComponent(voltarButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avaliarMusicasPanelLayout.createSequentialGroup()
                        .addGroup(avaliarMusicasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idReavaliacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idAvaliacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(avaliarMusicasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avaliarMusicasPanelLayout.createSequentialGroup()
                                .addComponent(avaliarNotaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(avaliarMusicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avaliarMusicasPanelLayout.createSequentialGroup()
                                .addComponent(reavaliarNotaTextField)
                                .addGap(18, 18, 18)
                                .addComponent(reavaliarMusicaButton)))))
                .addContainerGap())
        );
        avaliarMusicasPanelLayout.setVerticalGroup(
            avaliarMusicasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avaliarMusicasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarButton)
                .addGap(18, 18, 18)
                .addComponent(minhasAvaliacoesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(avaliarMusicasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reavaliarNotaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(reavaliarMusicaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idReavaliacaoTextField))
                .addGap(32, 32, 32)
                .addComponent(escolhaAMusicaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(avaliarMusicasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avaliarNotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avaliarMusicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idAvaliacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avaliarMusicasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avaliarMusicasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        DashboardTela db = new DashboardTela();
               db.setVisible(true);
               this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void avaliarMusicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarMusicaButtonActionPerformed
        // TODO add your handling code here:
        int escolha = JOptionPane.showConfirmDialog(null, "Confirmar avaliação?");
        if (escolha == JOptionPane.YES_OPTION){
            try{
                int id_musica = Integer.parseInt(idAvaliacaoTextField.getText());
                int nota_usuario = Integer.parseInt(avaliarNotaTextField.getText());
                UsuarioAvalia usuarioavalia = new UsuarioAvalia();
                usuarioavalia.setIdMusica(id_musica);
                usuarioavalia.setNotaUsuario(/*3/*usuariotemgenero.getIdGenero()*/nota_usuario);
                usuarioavalia.setIdUsuario(/*1*/Usuario.getInstance().getIdUsuario());
                UsuarioAvaliaDAO.avaliarMusica(usuarioavalia);
                UsuarioAvaliaDAO.atualizarMediaMusica(usuarioavalia);
                JOptionPane.showMessageDialog(null, "Música avaliada");
                buscarMusicas();
                buscarMinhasAvaliacoes();
                avaliarNotaTextField.setText("");
                reavaliarNotaTextField.setText("");
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Algo deu errado. Tente novamente mais tarde.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Tá bom.");
        }
    }//GEN-LAST:event_avaliarMusicaButtonActionPerformed

    private void escolhaAMusicaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolhaAMusicaComboBoxActionPerformed
        // TODO add your handling code here:
        Musica musica = (Musica)escolhaAMusicaComboBox.getSelectedItem();
        avaliarNotaTextField.setText(Integer.toString(musica.getNotaUsuario()));
        idAvaliacaoTextField.setText(Integer.toString(musica.getIdMusica()));
    }//GEN-LAST:event_escolhaAMusicaComboBoxActionPerformed

    private void reavaliarMusicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reavaliarMusicaButtonActionPerformed
        // TODO add your handling code here:
        int escolha = JOptionPane.showConfirmDialog(null, "Confirmar reavaliação?");
        if (escolha == JOptionPane.YES_OPTION){
            try{
                int id_musica = Integer.parseInt(idReavaliacaoTextField.getText());
                int nota_usuario = Integer.parseInt(reavaliarNotaTextField.getText());
                UsuarioAvalia usuarioavalia = new UsuarioAvalia();
                usuarioavalia.setIdMusica(id_musica);
                usuarioavalia.setNotaUsuario(/*3/*usuariotemgenero.getIdGenero()*/nota_usuario);
                usuarioavalia.setIdUsuario(/*1*/Usuario.getInstance().getIdUsuario());
                UsuarioAvaliaDAO.reavaliarMusica(usuarioavalia);
                UsuarioAvaliaDAO.atualizarMediaMusica(usuarioavalia);
                JOptionPane.showMessageDialog(null, "Música reavaliada");
                buscarMusicas();
                buscarMinhasAvaliacoes();
                reavaliarNotaTextField.setText("");
                avaliarNotaTextField.setText("");
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Algo deu errado. Tente novamente mais tarde.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Tá bom.");
        }
    }//GEN-LAST:event_reavaliarMusicaButtonActionPerformed

    private void minhasAvaliacoesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minhasAvaliacoesComboBoxActionPerformed
        // TODO add your handling code here:
        Musica musica = (Musica)minhasAvaliacoesComboBox.getSelectedItem();
        reavaliarNotaTextField.setText(Integer.toString(musica.getNotaUsuario()));
        idReavaliacaoTextField.setText(Integer.toString(musica.getIdMusica()));
    }//GEN-LAST:event_minhasAvaliacoesComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusicasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusicasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusicasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusicasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvaliarMusicasTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avaliarMusicaButton;
    private javax.swing.JPanel avaliarMusicasPanel;
    private javax.swing.JTextField avaliarNotaTextField;
    private javax.swing.JComboBox<Musica> escolhaAMusicaComboBox;
    private javax.swing.JTextField idAvaliacaoTextField;
    private javax.swing.JTextField idReavaliacaoTextField;
    private javax.swing.JComboBox<Musica> minhasAvaliacoesComboBox;
    private javax.swing.JButton reavaliarMusicaButton;
    private javax.swing.JTextField reavaliarNotaTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
