/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sistema_de_musicas;

import javax.swing.JOptionPane;

/**
 *
 * @author JFernandes
 */
public class CadastroTela extends javax.swing.JFrame {

    /**
     * Creates new form CadastroTela
     */
    public CadastroTela() {
        super ("Cadastro");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroPanel = new javax.swing.JPanel();
        escolhaUmNomeDeUsuarioTextField = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        escolhaUmaSenhaPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        escolhaUmNomeDeUsuarioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha um nome de usuário"));

        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        escolhaUmaSenhaPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha uma senha"));
        escolhaUmaSenhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolhaUmaSenhaPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroPanelLayout = new javax.swing.GroupLayout(cadastroPanel);
        cadastroPanel.setLayout(cadastroPanelLayout);
        cadastroPanelLayout.setHorizontalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escolhaUmaSenhaPasswordField)
                    .addComponent(escolhaUmNomeDeUsuarioTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                        .addComponent(voltarButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cadastroPanelLayout.setVerticalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarButton)
                .addGap(29, 29, 29)
                .addComponent(escolhaUmNomeDeUsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(escolhaUmaSenhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        // TODO add your handling code here:
        String nome_usuario = escolhaUmNomeDeUsuarioTextField.getText();
        String senha_usuario = new String(escolhaUmaSenhaPasswordField.getPassword());        
        if (nome_usuario == null || nome_usuario.length() <= 0 || senha_usuario == null || senha_usuario.length() <= 0){
            JOptionPane.showMessageDialog(null, "Olha, tem algo faltando");
            return;
        }
        try{
            int escolha = JOptionPane.showConfirmDialog(null, "Confirmar cadastro?");
            if (escolha == JOptionPane.YES_OPTION){
                Usuario usuario = new Usuario (nome_usuario, senha_usuario);
                UsuarioDAO.adicionarUsuario(usuario);
                //buscarCursos();
                JOptionPane.showMessageDialog(null, "Usuário cadastrado");
                escolhaUmNomeDeUsuarioTextField.setText("");
                escolhaUmaSenhaPasswordField.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "Tá bom");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Algo deu errado. Tente novamente mais tarde.");             
        }
        LoginTela l = new LoginTela();
               l.setVisible(true);
               this.dispose();
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        
        LoginTela log = new LoginTela();
               log.setVisible(true);
               this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void escolhaUmaSenhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolhaUmaSenhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escolhaUmaSenhaPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JPanel cadastroPanel;
    private javax.swing.JTextField escolhaUmNomeDeUsuarioTextField;
    private javax.swing.JPasswordField escolhaUmaSenhaPasswordField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
