/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sistema_de_musicas;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JFernandes
 */
public class RecomendacoesTela extends javax.swing.JFrame {

    /**
     * Creates new form RecomendacoesTela
     */
    public RecomendacoesTela() {
        super ("Recomendações");
        initComponents();
        buscarMusicasRecomendadas();
        setLocationRelativeTo(null);
    }
    
    private void buscarMusicasRecomendadas (){
        try{
            List <Musica> musicas = MusicaDAO.listarMusicasRecomendadas(Usuario.getInstance());
            recomendacoesComboBox.setModel(new DefaultComboBoxModel<>(musicas.toArray(new Musica[0])));
            
        }
        catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tente novamente mais tarde");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recomendacoesPanel = new javax.swing.JPanel();
        voltarButton = new javax.swing.JButton();
        recomendacoesComboBox = new javax.swing.JComboBox<>();
        postoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recomendacoesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Recomendações"));

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        recomendacoesComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Recomendações"));
        recomendacoesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recomendacoesComboBoxActionPerformed(evt);
            }
        });

        postoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Posto"));

        javax.swing.GroupLayout recomendacoesPanelLayout = new javax.swing.GroupLayout(recomendacoesPanel);
        recomendacoesPanel.setLayout(recomendacoesPanelLayout);
        recomendacoesPanelLayout.setHorizontalGroup(
            recomendacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recomendacoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recomendacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recomendacoesPanelLayout.createSequentialGroup()
                        .addComponent(recomendacoesComboBox, 0, 222, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(postoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(recomendacoesPanelLayout.createSequentialGroup()
                        .addComponent(voltarButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        recomendacoesPanelLayout.setVerticalGroup(
            recomendacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recomendacoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarButton)
                .addGap(18, 18, 18)
                .addGroup(recomendacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(postoTextField)
                    .addComponent(recomendacoesComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recomendacoesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recomendacoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        // TODO add your handling code here:
        DashboardTela db = new DashboardTela();
               db.setVisible(true);
               this.dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void recomendacoesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recomendacoesComboBoxActionPerformed
        // TODO add your handling code here:
        Musica musica = (Musica)recomendacoesComboBox.getSelectedItem();
        postoTextField.setText(Double.toString(musica.getMediaNotasMusica()));
    }//GEN-LAST:event_recomendacoesComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecomendacoesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecomendacoesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecomendacoesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecomendacoesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecomendacoesTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField postoTextField;
    private javax.swing.JComboBox<Musica> recomendacoesComboBox;
    private javax.swing.JPanel recomendacoesPanel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
